version: "3"

networks:
  loki:
    driver: bridge

services:
  loki:
    image: grafana/loki:2.4.1
    container_name: loki
    restart: unless-stopped
    expose:
      - 3100
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.4.1
    container_name: promtail
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    restart: unless-stopped
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    expose:
      - 3000
    volumes:
      - ./grafana/grafana_data:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    networks:
      - loki
  
  haproxy:
    image: haproxytech/haproxy-alpine:2.4
    container_name: haproxy
    volumes:
      - ./haproxy/etc:/usr/local/etc/haproxy:ro
    ports:
      - "3000:3000"
      - "3100:3100"
    restart: unless-stopped
    networks:
      - loki
#volumes:
#    grafana_data: {}
